<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="11" name="pytest" skips="0" tests="12" time="0.170"><testcase classname="test_submit.TestChalange2" file="test_submit.py" line="6" name="test_instance_class" time="0.0010380744934082031"></testcase><testcase classname="test_submit.TestChalange2" file="test_submit.py" line="10" name="test_protected_attribute_manager" time="0.0010023117065429688"><failure message="TypeError: __init__() takes 4 positional arguments but 5 were given">E   TypeError: __init__() takes 4 positional arguments but 5 were given</failure></testcase><testcase classname="test_submit.TestChalange2" file="test_submit.py" line="15" name="test_protected_attribute" time="0.0009984970092773438"><failure message="TypeError: __init__() takes 4 positional arguments but 5 were given">E   TypeError: __init__() takes 4 positional arguments but 5 were given</failure></testcase><testcase classname="test_submit.TestChalange2" file="test_submit.py" line="20" name="test_total_hours_seller" time="0.0"><failure message="TypeError: __init__() takes 4 positional arguments but 5 were given">E   TypeError: __init__() takes 4 positional arguments but 5 were given</failure></testcase><testcase classname="test_submit.TestChalange2" file="test_submit.py" line="24" name="test_total_hours_manager" time="0.0"><failure message="TypeError: __init__() takes 4 positional arguments but 5 were given">E   TypeError: __init__() takes 4 positional arguments but 5 were given</failure></testcase><testcase classname="test_submit.TestChalange2" file="test_submit.py" line="28" name="test_get_department_seller" time="0.0009844303131103516"><failure message="TypeError: __init__() takes 4 positional arguments but 5 were given">E   TypeError: __init__() takes 4 positional arguments but 5 were given</failure></testcase><testcase classname="test_submit.TestChalange2" file="test_submit.py" line="32" name="test_get_department_manager" time="0.001032114028930664"><failure message="TypeError: __init__() takes 4 positional arguments but 5 were given">E   TypeError: __init__() takes 4 positional arguments but 5 were given</failure></testcase><testcase classname="test_submit.TestChalange2" file="test_submit.py" line="36" name="test_sales_seller" time="0.0"><failure message="TypeError: __init__() takes 4 positional arguments but 5 were given">E   TypeError: __init__() takes 4 positional arguments but 5 were given</failure></testcase><testcase classname="test_submit.TestChalange2" file="test_submit.py" line="42" name="test_protected_attribute_sales" time="0.0019969940185546875"><failure message="TypeError: __init__() takes 4 positional arguments but 5 were given">E   TypeError: __init__() takes 4 positional arguments but 5 were given</failure></testcase><testcase classname="test_submit.TestChalange2" file="test_submit.py" line="47" name="test_calc_bonus_seller" time="0.0"><failure message="TypeError: __init__() takes 4 positional arguments but 5 were given">E   TypeError: __init__() takes 4 positional arguments but 5 were given</failure></testcase><testcase classname="test_submit.TestChalange2" file="test_submit.py" line="53" name="test_calc_bonus_manger" time="0.0009965896606445312"><failure message="TypeError: __init__() takes 4 positional arguments but 5 were given">E   TypeError: __init__() takes 4 positional arguments but 5 were given</failure></testcase><testcase classname="test_submit.TestChalange2" file="test_submit.py" line="57" name="test_get_sales_manger" time="0.0010728836059570312"><failure message="TypeError: __init__() takes 4 positional arguments but 5 were given">E   TypeError: __init__() takes 4 positional arguments but 5 were given</failure></testcase></testsuite>